[package]
name = "suipump"
version = "0.3.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet", override = true }
CetusClmm = { local = "C:/Users/User/Desktop/cetus-contracts/packages/cetus_clmm", override = true }

[addresses]
suipump = "0x0"
